// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJvbXNpF4x6FPx7WtyhF9LIn771VgIQjk',
    appId: '1:283384934477:web:91dfc94f0e973e00a4ec04',
    messagingSenderId: '283384934477',
    projectId: 'adventurehub-24947',
    authDomain: 'adventurehub-24947.firebaseapp.com',
    storageBucket: 'adventurehub-24947.appspot.com',
    measurementId: 'G-JK60S0LSSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnnNWCVDLYg5ohOPlnWQm1YwOPRNvK6Xc',
    appId: '1:283384934477:android:1c98958ae289c2f5a4ec04',
    messagingSenderId: '283384934477',
    projectId: 'adventurehub-24947',
    storageBucket: 'adventurehub-24947.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFvMwfzdTcFrSxGayOaZiOVsMOeX17ymg',
    appId: '1:283384934477:ios:a8cda05f188a5684a4ec04',
    messagingSenderId: '283384934477',
    projectId: 'adventurehub-24947',
    storageBucket: 'adventurehub-24947.appspot.com',
    iosBundleId: 'com.example.adventurehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFvMwfzdTcFrSxGayOaZiOVsMOeX17ymg',
    appId: '1:283384934477:ios:a8cda05f188a5684a4ec04',
    messagingSenderId: '283384934477',
    projectId: 'adventurehub-24947',
    storageBucket: 'adventurehub-24947.appspot.com',
    iosBundleId: 'com.example.adventurehub',
  );
}
